spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    username: "${DB_USERNAME:subscriptiontrackerapi}"
    password: "${DB_PASSWORD:subscriptiontrackerapi}"
    type: com.zaxxer.hikari.HikariDataSource
    url: "jdbc:postgresql://${DB_HOST:localhost}:5432/subscriptiontrackerapi"

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: update

server:
  port: 8080


jwt:
  secret: "${JWT_SECRET:secret}"
